name: Run Me CLI Sunset 6-Hourly

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
  
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      env:
        
        RAW_ENV: ${{ secrets.ENV_FILE }}
      run: |
        cat << 'EOF' > .env
        $RAW_ENV
        EOF
    - name: Run Script
      run: python main.py
